// lib/firebase_options.dart
// Generated by FlutterFire CLI — do not edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEa-0FRvx7zwfhgDqlr91aF-oSUApCWic',
    appId: '1:492850431837:web:c1aa8837c5b93e73d60ab4',
    messagingSenderId: '492850431837',
    projectId: 'clubnight-ba39f',
    authDomain: 'clubnight-ba39f.firebaseapp.com',
    storageBucket: 'clubnight-ba39f.firebasestorage.app',
    measurementId: 'G-PLCMJ2374E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfL6GKQ-ln6al0cgrIWQN1AWoMeULGnA',
    appId: '1:492850431837:android:4baf77fbcc930774d60ab4',
    messagingSenderId: '492850431837',
    projectId: 'clubnight-ba39f',
    storageBucket: 'clubnight-ba39f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx-dG1dzDUL4GF6q8Jtflw4u6iBJOFfQ8',
    appId: '1:492850431837:ios:c97525773ece1879d60ab4',
    messagingSenderId: '492850431837',
    projectId: 'clubnight-ba39f',
    storageBucket: 'clubnight-ba39f.firebasestorage.app',
    iosBundleId: 'com.cltc.squashsocial',
  );

  // macOS uses the same SDK as iOS — add a macOS Firebase app in the
  // Firebase console and run flutterfire configure again to populate this.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx-dG1dzDUL4GF6q8Jtflw4u6iBJOFfQ8',
    appId: '1:492850431837:ios:c97525773ece1879d60ab4',
    messagingSenderId: '492850431837',
    projectId: 'clubnight-ba39f',
    storageBucket: 'clubnight-ba39f.firebasestorage.app',
    iosBundleId: 'com.cltc.squashsocial',
  );

  // Flutter Windows uses the Web Firebase SDK.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEa-0FRvx7zwfhgDqlr91aF-oSUApCWic',
    appId: '1:492850431837:web:c1aa8837c5b93e73d60ab4',
    messagingSenderId: '492850431837',
    projectId: 'clubnight-ba39f',
    authDomain: 'clubnight-ba39f.firebaseapp.com',
    storageBucket: 'clubnight-ba39f.firebasestorage.app',
    measurementId: 'G-PLCMJ2374E',
  );
}
